spring:
  application:
    name: alpha-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
#    enabled: true
    sampler:
      percentage: 1.0
server:
  port: 9901

eureka:
  instance:
    # 心跳时间
    lease-renewal-interval-in-seconds: 5
    # 发呆时间
    lease-expiration-duration-in-seconds: 10
    # 使用IP
    prefer-ip-address: true
    # 实例名称格式
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    # 注册信息获取间隔时间
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka.airi.net.cn/eureka
info:
  version: '@pom.version@'
  info: ${spring.application.name}

